language: csharp
sudo: false
dist: trusty
env:
  global:
    # We want to build our product in Release configuration
    - CONFIGURATION=Release
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    # Disable sending usage data to Microsoft
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    # Skip xml docs for packages
    - NUGET_XMLDOC_MODE=skip
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build ./Plex.Server.Webhooks/
  - dotnet test ./Plex.Server.Webhooks.Tests/