language: csharp
sudo: false
dist: trusty
env:
  global:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    # Disable sending usage data to Microsoft
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build ./Plex.Server.Webhooks/
  - dotnet test ./Plex.Server.Webhooks.Tests/